### ISSUE TITLE
Tge port to ux-dx

### ISSUE THREAD

**Issue by dudochkin-victor** [TakWolf/tge#2]
I just ported the tge from 'glow' to 'ux-dx'. And I put it in `ux-dx`.
I would like to know your opinion on this matter. I hope there will be no problems with licensing.
I have my own vision of a general purpose 3D library, so I developed ux-dx, which is OpenGL ES 2.0 / 3.0 + binding at the moment.
I will also be glad if you join the ux-dx project.

**Comment by TakWolf** [comment]
Is this: https://github.com/angular-rust/ux-dx ?

It seems interesting, please let me take some time to research it.

What's the abstraction level difference between ux-dx, glow and https://github.com/gfx-rs/wgpu?

--------------

But tge just an experimental project, with the common way to implement basic 2d texture rendering, without any unique ideas.
